### ISSUE TITLE
Example program keep throwing errors

### ISSUE THREAD

**Issue by sras** [positiondev/hworker#2]
When I tried to run the provided example program, it keeps throwing some kind of error in the ghci console..

```
("printer",Error "ERR Error running script (call to f_d8424197f58524dcab68d7b0
31392c35e4692bfb): @user_script:3: @user_script: 3: Lua redis() command arguments must be strings or integers ")
```

**Comment by emhoracek** [comment]
@sras Sorry it took so incredibly long for me to see this! Hworker currently only works for Redis 2.8 and it needs updated to work with the latest Redis.
